# Generated by Django 5.0 manually

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructureasset",
            name="data_owner",
            field=models.CharField(
                blank=True,
                help_text="Organization that owns the data (e.g., Ministry of Health)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="infrastructureasset",
            name="update_frequency",
            field=models.CharField(
                blank=True,
                help_text="Frequency of data updates (e.g., Annual, Monthly)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="infrastructureasset",
            name="license",
            field=models.CharField(
                blank=True,
                help_text="Data license (e.g., CC-BY-4.0)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="infrastructureasset",
            name="source_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Raw metadata from the source for auditability",
            ),
        ),
    ]
