# Generated by Django 5.2.11 on 2026-02-16 22:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="infrastructureasset",
            new_name="infrastruct_asset_t_6bfdd5_idx",
            old_name="asset_type_area_idx",
        ),
        migrations.RenameIndex(
            model_name="infrastructureasset",
            new_name="infrastruct_conditi_00afb2_idx",
            old_name="asset_condition_idx",
        ),
        migrations.RenameIndex(
            model_name="infrastructureasset",
            new_name="infrastruct_is_veri_3e33cb_idx",
            old_name="asset_verified_idx",
        ),
        migrations.AddField(
            model_name="infrastructureasset",
            name="data_owner",
            field=models.CharField(
                blank=True,
                help_text="Organization that owns the data (e.g., Ministry of Health)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="infrastructureasset",
            name="license",
            field=models.CharField(
                blank=True, help_text="Data license (e.g., CC-BY-4.0)", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="infrastructureasset",
            name="source_metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Raw metadata from the source for auditability"
            ),
        ),
        migrations.AddField(
            model_name="infrastructureasset",
            name="update_frequency",
            field=models.CharField(
                blank=True,
                help_text="Frequency of data updates (e.g., Annual, Monthly)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="infrastructureasset",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
